### ISSUE TITLE
Cabal Dependencey

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ekmett/either#62]
When compiling this package with stack it requires me to compile Cabal which takes forever.
Is it possible to remove Cabal as a dependency?

**Comment by piq9117** [comment]
I don't see `Cabal` as a dependency anymore. Maybe we can close?

**Comment by RyanGlScott** [comment]
I suspect that the `Cabal` dependency was incurred due to the use of `cabal-doctest` in some of `either`'s dependencies (e.g., `bifunctors`). None of `either`'s dependencies use `cabal-doctest` anymore, so there shouldn't be any reason why `either` depends on `Cabal` currently. As such, I'll close this issue, but please re-open if I'm mistaken.
